export default [
  {
    label: "Hector",
    last_name: "Bellerin",
    team: "Arsenal",
    position: "Defender",
    image: "hectorbellerin.jpg",
  },
  {
    label: "Petr",
    last_name: "Cech",
    team: "Arsenal",
    position: "Goalkeeper",
    image: "petrcech.jpg",
  },
  {
    label: "Olivier",
    last_name: "Giroud",
    team: "Arsenal",
    position: "Striker",
    image: "oliviergiroud.jpg",
  },
  {
    label: "Alex",
    last_name: "Iwobi",
    team: "Arsenal",
    position: "Midfielder 2",
    image: "alexiwobi.jpg",
  },
  {
    label: "Laurent",
    last_name: "Koscielny",
    team: "Arsenal",
    position: "Defender",
    image: "laurentkoscielny.jpg",
  },
  {
    label: "Mesut",
    last_name: "Ozil",
    team: "Arsenal",
    position: "Midfielder 1",
    image: "mesutozil.jpg",
  },
  {
    label: "Alexis",
    last_name: "Sanchez",
    team: "Arsenal",
    position: "Striker",
    image: "alexissanchez.jpg",
  },
  {
    label: "Theo",
    last_name: "Walcott",
    team: "Arsenal",
    position: "Midfielder 2",
    image: "theowalcott.jpg",
  },
  {
    label: "Marcos",
    last_name: "Alonso",
    team: "Chelsea",
    position: "Defender",
    image: "marcosalonso.jpg",
  },
  {
    label: "Cesar",
    last_name: "Azpilicueta",
    team: "Chelsea",
    position: "Defender",
    image: "cesarazpilicueta.jpg",
  },
  {
    label: "Gary",
    last_name: "Cahill",
    team: "Chelsea",
    position: "Defender",
    image: "garycahill.jpg",
  },
  {
    label: "Diego",
    last_name: "Costa",
    team: "Chelsea",
    position: "Striker",
    image: "diegocosta.jpg",
  },
  {
    label: "Thibaut",
    last_name: "Courtois",
    team: "Chelsea",
    position: "Goalkeeper",
    image: "thibautcourtois.jpg",
  },
  {
    label: "Eden",
    last_name: "Hazard",
    team: "Chelsea",
    position: "Midfielder 1",
    image: "edenhazard.jpg",
  },
  {
    label: "Nemanja",
    last_name: "Matic",
    team: "Chelsea",
    position: "Midfielder 2",
    image: "nemanjamatic.jpg",
  },
  {
    label: "Victor",
    last_name: "Moses",
    team: "Chelsea",
    position: "Midfielder 2",
    image: "victormoses.jpg",
  },
  {
    label: "Willian",
    team: "Chelsea",
    position: "Midfielder 1",
    image: "willian.jpg",
  },
  {
    label: "Christian",
    last_name: "Benteke",
    team: "Crystal Palace",
    position: "Striker",
    image: "christianbenteke.jpg",
  },
  {
    label: "Daniel",
    last_name: "Amartey",
    team: "Leicester",
    position: "Midfielder 2",
    image: "danielamartey.jpg",
  },
  {
    label: "Robert",
    last_name: "Huth",
    team: "Leicester",
    position: "Defender",
    image: "roberthuth.jpg",
  },
  {
    label: "Riyad",
    last_name: "Mahrez",
    team: "Leicester",
    position: "Midfielder 2",
    image: "riyadmahrez.jpg",
  },
  {
    label: "Wes",
    last_name: "Morgan",
    team: "Leicester",
    position: "Defender",
    image: "wesmorgan.jpg",
  },
  {
    label: "Kasper",
    last_name: "Schmeichel",
    team: "Leicester",
    position: "Goalkeeper",
    image: "kasperschmeichel.jpg",
  },
  {
    label: "Islam",
    last_name: "Slimani",
    team: "Leicester",
    position: "Striker",
    image: "islamslimani.jpg",
  },
  {
    label: "Jamie",
    last_name: "Vardy",
    team: "Leicester",
    position: "Striker",
    image: "jamievardy.jpg",
  },
  {
    label: "Sergio",
    last_name: "Aguero",
    team: "Manchester City",
    position: "Striker",
    image: "sergioaguero.jpg",
  },
];
