export default [
  {
    stage: "Grunddurchgang",
    label: "2020-09-11",
    round: "1. Runde",
    team1: "SK Rapid Wien",
    team2: "FC Admira Wacker Mödling",
    score: {
      ft: [4, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    label: "2020-09-11",
    round: "1. Runde",
    team1: "LASK Linz",
    team2: "FK Austria Wien",
    score: {
      ft: [1, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "1. Runde",
    label: "2020-09-12",
    team1: "SCR Altach",
    team2: "TSV Hartberg",
    score: {
      ft: [1, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "1. Runde",
    label: "2020-09-13",
    team1: "SV Ried",
    team2: "WSG Tirol",
    score: {
      ft: [3, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "1. Runde",
    label: "2020-09-13",
    team1: "SKN St. Pölten",
    team2: "SK Sturm Graz",
    score: {
      ft: [0, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "1. Runde",
    label: "2020-09-13",
    team1: "Wolfsberger AC",
    team2: "FC RB Salzburg",
    score: {
      ft: [1, 3],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "2. Runde",
    label: "2020-09-19",
    team1: "FC RB Salzburg",
    team2: "SCR Altach",
    score: {
      ft: [4, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "2. Runde",
    label: "2020-09-19",
    team1: "WSG Tirol",
    team2: "LASK Linz",
    score: {
      ft: [1, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "2. Runde",
    label: "2020-09-19",
    team1: "SK Sturm Graz",
    team2: "SK Rapid Wien",
    score: {
      ft: [1, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "2. Runde",
    label: "2020-09-20",
    team1: "TSV Hartberg",
    team2: "Wolfsberger AC",
    score: {
      ft: [0, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "2. Runde",
    label: "2020-09-20",
    team1: "FC Admira Wacker Mödling",
    team2: "SKN St. Pölten",
    score: {
      ft: [0, 5],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "2. Runde",
    label: "2020-09-20",
    team1: "FK Austria Wien",
    team2: "SV Ried",
    score: {
      ft: [2, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "3. Runde",
    label: "2020-09-26",
    team1: "SCR Altach",
    team2: "WSG Tirol",
    score: {
      ft: [0, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "3. Runde",
    label: "2020-09-26",
    team1: "SKN St. Pölten",
    team2: "SK Rapid Wien",
    score: {
      ft: [1, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "3. Runde",
    label: "2020-09-26",
    team1: "SV Ried",
    team2: "FC RB Salzburg",
    score: {
      ft: [1, 3],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "3. Runde",

    label: "2020-09-27",
    team1: "FK Austria Wien",
    team2: "FC Admira Wacker Mödling",
    score: {
      ft: [2, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "3. Runde",
    label: "2020-09-27",
    team1: "TSV Hartberg",
    team2: "SK Sturm Graz",
    score: {
      ft: [1, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "3. Runde",
    label: "2020-09-27",
    team1: "LASK Linz",
    team2: "Wolfsberger AC",
    score: {
      ft: [3, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "4. Runde",
    label: "2020-10-03",
    team1: "FC Admira Wacker Mödling",
    team2: "SV Ried",
    score: {
      ft: [3, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "4. Runde",
    label: "2020-10-03",
    team1: "WSG Tirol",
    team2: "FK Austria Wien",
    score: {
      ft: [0, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "4. Runde",
    label: "2020-10-03",
    team1: "Wolfsberger AC",
    team2: "SKN St. Pölten",
    score: {
      ft: [2, 4],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "4. Runde",
    label: "2020-10-04",
    team1: "SK Sturm Graz",
    team2: "SCR Altach",
    score: {
      ft: [4, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "4. Runde",
    label: "2020-10-04",
    team1: "FC RB Salzburg",
    team2: "TSV Hartberg",
    score: {
      ft: [7, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "4. Runde",
    label: "2020-10-04",
    team1: "SK Rapid Wien",
    team2: "LASK Linz",
    score: {
      ft: [3, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "5. Runde",
    label: "2020-10-24",
    team1: "FK Austria Wien",
    team2: "FC RB Salzburg",
    score: {
      ft: [0, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "5. Runde",
    label: "2020-10-24",
    team1: "SCR Altach",
    team2: "FC Admira Wacker Mödling",
    score: {
      ft: [4, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "5. Runde",
    label: "2020-10-24",
    team1: "SV Ried",
    team2: "SK Sturm Graz",
    score: {
      ft: [0, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "5. Runde",
    label: "2020-10-25",
    team1: "LASK Linz",
    team2: "SKN St. Pölten",
    score: {
      ft: [4, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "5. Runde",
    label: "2020-10-25",
    team1: "WSG Tirol",
    team2: "TSV Hartberg",
    score: {
      ft: [1, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "5. Runde",
    label: "2020-10-25",
    team1: "Wolfsberger AC",
    team2: "SK Rapid Wien",
    score: {
      ft: [3, 4],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "6. Runde",
    label: "2020-10-31",
    team1: "FC RB Salzburg",

    team2: "WSG Tirol",
    score: {
      ft: [5, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "6. Runde",
    label: "2020-10-31",
    team1: "TSV Hartberg",
    team2: "FK Austria Wien",
    score: {
      ft: [2, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "6. Runde",
    label: "2020-10-31",
    team1: "SKN St. Pölten",
    team2: "SV Ried",
    score: {
      ft: [4, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "6. Runde",
    label: "2020-11-01",
    team1: "SK Rapid Wien",
    team2: "SCR Altach",
    score: {
      ft: [3, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "6. Runde",
    label: "2020-11-01",
    team1: "FC Admira Wacker Mödling",
    team2: "Wolfsberger AC",
    score: {
      ft: [1, 3],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "6. Runde",
    label: "2020-11-01",
    team1: "SK Sturm Graz",
    team2: "LASK Linz",
    score: {
      ft: [0, 2],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "7. Runde",
    label: "2020-11-07",
    team1: "SCR Altach",
    team2: "FK Austria Wien",
    score: {
      ft: [0, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "7. Runde",
    label: "2020-11-07",
    team1: "SKN St. Pölten",
    team2: "WSG Tirol",
    score: {
      ft: [0, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "7. Runde",
    label: "2020-11-07",
    team1: "SV Ried",
    team2: "TSV Hartberg",
    score: {
      ft: [2, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "7. Runde",
    label: "2020-11-08",
    team1: "Wolfsberger AC",
    team2: "SK Sturm Graz",
  },
  {
    stage: "Grunddurchgang",
    round: "7. Runde",
    label: "2020-11-08",
    team1: "LASK Linz",
    team2: "FC Admira Wacker Mödling",
    score: {
      ft: [4, 0],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "7. Runde",
    label: "2020-11-08",
    team1: "SK Rapid Wien",
    team2: "FC RB Salzburg",
    score: {
      ft: [1, 1],
    },
  },
  {
    stage: "Grunddurchgang",
    round: "8. Runde",
    label: "2020-11-21",
    team1: "FC RB Salzburg",
    team2: "SK Sturm Graz",
  },
  {
    stage: "Grunddurchgang",
    round: "8. Runde",
    label: "2020-11-21",
    team1: "TSV Hartberg",
    team2: "LASK Linz",
  },
  {
    stage: "Grunddurchgang",
    round: "8. Runde",
    label: "2020-11-21",
    team1: "SCR Altach",
    team2: "Wolfsberger AC",
  },
  {
    stage: "Grunddurchgang",
    round: "8. Runde",
    label: "2020-11-22",
    team1: "FK Austria Wien",
    team2: "SKN St. Pölten",
  },
  {
    stage: "Grunddurchgang",
    round: "8. Runde",
    label: "2020-11-22",
    team1: "WSG Tirol",
    team2: "FC Admira Wacker Mödling",
  },
  {
    stage: "Grunddurchgang",
    round: "8. Runde",
    label: "2020-11-22",
    team1: "SV Ried",
    team2: "SK Rapid Wien",
  },
  {
    stage: "Grunddurchgang",
    round: "9. Runde",
    label: "2020-11-28",
    team1: "SK Sturm Graz",
    team2: "WSG Tirol",
  },
  {
    stage: "Grunddurchgang",
    round: "9. Runde",
    label: "2020-11-28",
    team1: "SKN St. Pölten",
    team2: "FC RB Salzburg",
  },
  {
    stage: "Grunddurchgang",
    round: "9. Runde",
    label: "2020-11-28",
    team1: "FC Admira Wacker Mödling",
    team2: "TSV Hartberg",
  },
  {
    stage: "Grunddurchgang",
    round: "9. Runde",
    label: "2020-11-29",
    team1: "Wolfsberger AC",
    team2: "SV Ried",
  },
  {
    stage: "Grunddurchgang",
    round: "9. Runde",
    label: "2020-11-29",
    team1: "LASK Linz",
    team2: "SCR Altach",
  },
  {
    stage: "Grunddurchgang",
    round: "9. Runde",
    label: "2020-11-29",
    team1: "SK Rapid Wien",
    team2: "FK Austria Wien",
  },
  {
    stage: "Grunddurchgang",
    round: "10. Runde",
    label: "2020-12-05",
    team1: "FK Austria Wien",
    team2: "SK Sturm Graz",
  },
  {
    stage: "Grunddurchgang",
    round: "10. Runde",
    label: "2020-12-05",
    team1: "SCR Altach",
    team2: "SKN St. Pölten",
  },
  {
    stage: "Grunddurchgang",
    round: "10. Runde",
    label: "2020-12-05",
    team1: "FC Admira Wacker Mödling",
    team2: "FC RB Salzburg",
  },
  {
    stage: "Grunddurchgang",
    round: "10. Runde",
    label: "2020-12-06",
    team1: "TSV Hartberg",
    team2: "SK Rapid Wien",
  },
  {
    stage: "Grunddurchgang",
    round: "10. Runde",
    label: "2020-12-06",
    team1: "WSG Tirol",
    team2: "Wolfsberger AC",
  },
  {
    stage: "Grunddurchgang",
    round: "10. Runde",
    label: "2020-12-06",
    team1: "LASK Linz",
    team2: "SV Ried",
  },
  {
    stage: "Grunddurchgang",
    round: "11. Runde",
    label: "2020-12-12",
    team1: "SK Sturm Graz",
    team2: "FC Admira Wacker Mödling",
  },
  {
    stage: "Grunddurchgang",
    round: "11. Runde",
    label: "2020-12-12",
    team1: "SKN St. Pölten",
    team2: "TSV Hartberg",
  },
  {
    stage: "Grunddurchgang",
    round: "11. Runde",
    label: "2020-12-12",
    team1: "SV Ried",
    team2: "SCR Altach",
  },
  {
    stage: "Grunddurchgang",
    round: "11. Runde",
    label: "2020-12-13",
    team1: "SK Rapid Wien",
    team2: "WSG Tirol",
  },
  {
    stage: "Grunddurchgang",
    round: "11. Runde",
    label: "2020-12-13",
    team1: "Wolfsberger AC",
    team2: "FK Austria Wien",
  },
  {
    stage: "Grunddurchgang",
    round: "11. Runde",
    label: "2020-12-13",
    team1: "FC RB Salzburg",
    team2: "LASK Linz",
  },
  {
    stage: "Grunddurchgang",
    round: "12. Runde",
    label: "2020-12-19",
    team1: "TSV Hartberg",
    team2: "SCR Altach",
  },
  {
    stage: "Grunddurchgang",
    round: "12. Runde",
    label: "2020-12-19",
    team1: "FC Admira Wacker Mödling",
    team2: "SK Rapid Wien",
  },
  {
    stage: "Grunddurchgang",
    round: "12. Runde",
    label: "2020-12-19",
    team1: "SK Sturm Graz",
    team2: "SKN St. Pölten",
  },
  {
    stage: "Grunddurchgang",
    round: "12. Runde",
    label: "2020-12-20",
    team1: "WSG Tirol",
    team2: "SV Ried",
  },
  {
    stage: "Grunddurchgang",
    round: "12. Runde",
    label: "2020-12-20",
    team1: "FC RB Salzburg",
    team2: "Wolfsberger AC",
  },
  {
    stage: "Grunddurchgang",
    round: "12. Runde",
    label: "2020-12-20",
    team1: "FK Austria Wien",
    team2: "LASK Linz",
  },
  {
    stage: "Grunddurchgang",
    round: "13. Runde",
    label: "2021-01-23",
    team1: "SCR Altach",
    team2: "FC RB Salzburg",
  },
  {
    stage: "Grunddurchgang",
    round: "13. Runde",
    label: "2021-01-23",
    team1: "LASK Linz",
    team2: "WSG Tirol",
  },
  {
    stage: "Grunddurchgang",
    round: "13. Runde",
    label: "2021-01-23",
    team1: "SK Rapid Wien",
    team2: "SK Sturm Graz",
  },
  {
    stage: "Grunddurchgang",
    round: "13. Runde",
    label: "2021-01-23",
    team1: "Wolfsberger AC",
    team2: "TSV Hartberg",
  },
  {
    stage: "Grunddurchgang",
    round: "13. Runde",
    label: "2021-01-23",
    team1: "SKN St. Pölten",
    team2: "FC Admira Wacker Mödling",
  },
];
